### ISSUE TITLE
Type Id

### ISSUE THREAD

**Issue by jrans** [dwyl/joi-postgresql#12]
It would be nice to be able to just specify type id and for abase to do the following stuff:
 + [x] Specify type of field (based on what kind of IDs we generate)
 + [x] Make field the primary key
 + [x] Not require id to be given on insert and instead returned
 + [x] Guarantee unique ids

Id generation and unique ids can be achieved in many way like incrementing a counter but for some that may not be ideal as:
 + It indicates the number of items in db
 + It is easy to guess ids
 + Tables would have overlapping sets of ids which may not be desired and would needs prefixing instead but if that were the case we may have something that also solves teh above problem.

This is not a new problem and hopefully there is a popular postgres add on that we can use!

@nelsonic Think this is a good start to the id discussion!

**Comment by jrans** [comment]
> SQL Server has some fixes for this with the uniqueidentifier data type and the newsequentialid() default value (which creates sortable GUIDs) - and that helps, but it still requires a lot more work then using a simple integer-based, auto-incrementing key. Which is precisely why so many developers like to use them.

**Comment by jrans** [comment]
http://www.starkandwayne.com/blog/uuid-primary-keys-in-postgresql/

https://www.postgresql.org/docs/9.4/static/uuid-ossp.html

https://www.postgresql.org/docs/9.4/static/pgcrypto.html f25.5

**Comment by jrans** [comment]
might be overkill but I think  `uuid_generate_v1mc()` from the `uuid-ossp` extension is the best way forward as if done by us right means people won't have to worry. We could even offer types of id like incremental if desired. Only drawback may be the length but we could work on that, i think keeping everything safe is the key thing here

**Comment by nelsonic** [comment]
@jrans, yeah this would be a _sweet_ feature!
For generating UUIDs see: https://www.npmjs.com/package/aguid

**Comment by jrans** [comment]
yes but don't have the postgres integration..., may be a bit more work but worth it though as may save headaches with the build etc...

**Comment by nelsonic** [comment]
@jrans for now we can create the table _manually_ and then _think_ about how to implement a "generator" once the feature is working for the client project... 😉

**Comment by jrans** [comment]
fixed as of #14
