### ISSUE TITLE
OR queries

### ISSUE THREAD

**Issue by Danwhy** [dwyl/joi-postgresql#24]
As answered in https://github.com/dwyl/abase/issues/73, it's not currently possible to perform `OR` or `AND` `WHERE` queries. 

I'd find these quite useful in a current project, so I'd like to implement them if possible

**Comment by iteles** [comment]
@Danwhy This sounds great, please feel free to assign this to yourself and put in a PR! 😊

**Comment by Danwhy** [comment]
Will do :+1: I don't think I have access as a collaborator to assign it to myself though

**Comment by jrans** [comment]
closed with #28
